export const json = {
  title: "User Feedback Survey",
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "rating",
          name: "simplificationRating",
          title:
            "On a scale of one to five, how good do you think the simplification is performed?",
          isRequired: true,
          rateMin: 1,
          rateMax: 5,
          minRateDescription: "(Very bad)",
          maxRateDescription: "(Very good)",
        },
        {
          type: "comment",
          name: "feedbackComments",
          visibleIf: "{simplificationRating} != null",
          title:
            "Do you have any additional feedback you would like to give us?",
        },
        {
          name: "usedDifficultSentences",
          type: "boolean",
          defaultValue: false,
          visibleIf: "{simplificationRating} != null",
          title:
            "Did you use the difficult sentences generated by the tool, which are highlighted if you click the 'show difficult sentences' button?",
        },
        {
          type: "rating",
          name: "difficultSentencesRating",
          title:
            "On a scale of one to five, how good do you think the difficult sentences in the original text are identified?",
          isRequired: true,
          visibleIf: "{usedDifficultSentences} = true",
          rateMin: 1,
          rateMax: 5,
          minRateDescription: "(Very bad)",
          maxRateDescription: "(Very good)",
        },
      ],
    },
  ],

  completeText: "Send",
  completedHtml: "<h3>Thank you for your feedback</h3>",

  showQuestionNumbers: "off",
};
